export const postContants = {
  VIEW_POST_REQUEST: "VIEW_POST_REQUEST",
  VIEW_POST_FAILURE: "VIEW_POST_FAILURE",
  VIEW_POST_SUCCESS: "VIEW_POST_SUCCESS",

  VIEW_ALL_POST_REQUEST: "VIEW_ALL_POST_REQUEST",
  VIEW_ALL_POST_FAILURE: "VIEW_ALL_POST_FAILURE",
  VIEW_ALL_POST_SUCCESS: "VIEW_ALL_POST_SUCCESS",

  RESET_STATE: "RESET_STATE",
};

export const userContants = {
  EMAIL_CHECKER_REQUEST: "EMAIL_CHECKER_REQUEST",
  EMAIL_CHECKER_FAILURE: "EMAIL_CHECKER_FAILURE",
  EMAIL_CHECKER_SUCCESS: "EMAIL_CHECKER_SUCCESS",

  CHECK_USER_STATUS_REQUEST: "CHECK_USER_STATUS_REQUEST",
  CHECK_USER_STATUS_SUCCESS: "CHECK_USER_STATUS_SUCCESS",
  CHECK_USER_STATUS_FAILURE: "CHECK_USER_STATUS_FAILURE",

  UPDATE_STATE_REQUEST: "UPDATE_STATE_REQUEST",
  UPDATE_STATE_SUCCESS: "UPDATE_STATE_SUCCESS",

  USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",

  USER_IS_PRESENT_OR_NOT_REQUEST: "USER_IS_PRESENT_OR_NOT_REQUEST",
  USER_IS_PRESENT_OR_NOT_SUCCESS: "USER_IS_PRESENT_OR_NOT_SUCCESS",
  ADD_USER_REQUEST: "ADD_USER_REQUEST",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAILURE: "ADD_USER_FAILURE",
  GET_USER_PROFILE_REQUEST: "GET_USER_PROFILE_REQUEST",
  GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
  GET_USER_PROFILE_FAILURE: "GET_USER_PROFILE_FAILURE",
};

export const achievemntsConstant = {
  GET_ACHIVE_REQUEST: "GET_ACHIVE_REQUEST",
  GET_ACHIVE_SUCCESS: "GET_ACHIVE_SUCCESS",
  GET_ACHIVE_FAILURE: "GET_ACHIVE_FAILURE",
};

export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const placeConstants = {
  GET_STATE_REQUEST: "GET_STATE_REQUEST",
  GET_STATE_SUCCESS: "GET_STATE_SUCCESS",
  GET_STATE_FAILURE: "GET_STATE_FAILURE",

  GET_CITY_REQUEST: "GET_CITY_REQUEST",
  GET_CITY_SUCCESS: "GET_CITY_SUCCESS",
  GET_CITY_FAILURE: "GET_CITY_FAILURE",

  GET_DIST_REQUEST: "GET_DIST_REQUEST",
  GET_DIST_SUCCESS: "GET_DIST_SUCCESS",
  GET_DIST_FAILURE: "GET_DIST_FAILURE",

  CLEAN_CITY: "CLEAN_CITY",
  CLEAN_DISTRICT: "CLEAN_DISTRICT",

  CLEAN_ALL_STATE: "CLEAN_ALL_STATE",
};

export const jobConstruct = {
  ADD_JOB_REQUEST: "ADD_JOB_REQUEST",
  ADD_JOB_SUCCESS: "ADD_JOB_SUCCESS",
  ADD_JOB_FAILURE: "ADD_JOB_FAILURE",

  RESET_JOB: "RESET_JOB",
  GET_ALL_JOBS_REQUEST: "GET_ALL_JOBS_REQUEST",
  GET_ALL_JOBS_SUCCESS: "GET_ALL_JOBS_SUCCESS",
  GET_ALL_JOBS_FAILURE: "GET_ALL_JOBS_FAILURE",

  GET_JOB_REQUEST: "GET_JOB_REQUEST",
  GET_JOB_SUCCESS: "GET_JOB_SUCCESS",
  GET_JOB_FAILURE: "GET_JOB_FAILURE",

  GET_MY_JOB_REQUEST:"GET_MY_JOB_REQUEST",
  GET_MY_JOB_SUCCESS:"GET_MY_JOB_SUCCESS",
  GET_MY_JOB_FAILURE:"GET_MY_JOB_FAILURE",

};

export const jobApplyConstants = {
  JOB_APPLY_REQUEST: "JOB_APPLY_REQUEST",
  JOB_APPLY_SUCCESS: "JOB_APPLY_SUCCESS",
  JOB_APPLY_FAILURE: "JOB_APPLY_FAILURE",

  GET_APPLYED_USERS_REQUEST:"GET_APPLYED_USERS_REQUEST",
  GET_APPLYED_USERS_SUCCESS:"GET_APPLYED_USERS_SUCCESS",
  GET_APPLYED_USERS_FAILURE:"GET_APPLYED_USERS_FAILURE",
};
