export const postContants = {
  VIEW_POST_REQUEST: "VIEW_POST_REQUEST",
  VIEW_POST_FAILURE: "VIEW_POST_FAILURE",
  VIEW_POST_SUCCESS: "VIEW_POST_SUCCESS",

  VIEW_ALL_POST_REQUEST: "VIEW_ALL_POST_REQUEST",
  VIEW_ALL_POST_FAILURE: "VIEW_ALL_POST_FAILURE",
  VIEW_ALL_POST_SUCCESS: "VIEW_ALL_POST_SUCCESS",

  RESET_STATE: "RESET_STATE",
};

export const userContants = {
  EMAIL_CHECKER_REQUEST: "EMAIL_CHECKER_REQUEST",
  EMAIL_CHECKER_FAILURE: "EMAIL_CHECKER_FAILURE",
  EMAIL_CHECKER_SUCCESS: "EMAIL_CHECKER_SUCCESS",

  UPDATE_STATE_REQUEST: "UPDATE_STATE_REQUEST",
  UPDATE_STATE_SUCCESS: "UPDATE_STATE_SUCCESS",

  USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",

  USER_IS_PRESENT_OR_NOT_REQUEST: "USER_IS_PRESENT_OR_NOT_REQUEST",
  USER_IS_PRESENT_OR_NOT_SUCCESS: "USER_IS_PRESENT_OR_NOT_SUCCESS",
  ADD_USER_REQUEST: "ADD_USER_REQUEST",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAILURE: "ADD_USER_FAILURE",
  GET_USER_PROFILE_REQUEST: "GET_USER_PROFILE_REQUEST",
  GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
  GET_USER_PROFILE_FAILURE: "GET_USER_PROFILE_FAILURE",
};

export const achievemntsConstant = {
  GET_ACHIVE_REQUEST: "GET_ACHIVE_REQUEST",
  GET_ACHIVE_SUCCESS: "GET_ACHIVE_SUCCESS",
  GET_ACHIVE_FAILURE: "GET_ACHIVE_FAILURE",
};

export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
};
