export const postContants = {
  VIEW_POST_REQUEST: "VIEW_POST_REQUEST",
  VIEW_POST_FAILURE: "VIEW_POST_FAILURE",
  VIEW_POST_SUCCESS: "VIEW_POST_SUCCESS",

  VIEW_ALL_POST_REQUEST: "VIEW_ALL_POST_REQUEST",
  VIEW_ALL_POST_FAILURE: "VIEW_ALL_POST_FAILURE",
  VIEW_ALL_POST_SUCCESS: "VIEW_ALL_POST_SUCCESS",

  RESET_STATE: "RESET_STATE",
};
